name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            libsqlite3-dev \
            libjpeg-dev \
            zlib1g-dev \
            git \
            openjdk-11-jdk \
            unzip \
            python3-pip
          pip3 install --upgrade cython==0.29.33
          pip3 install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: pupchat-apk
          path: bin/*.ap
